{
 "title": "Vaccinations",
 "time": { "from": "2021-01-01T00:00:00.000Z", "to": "2021-03-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Utilisation des vaccins disponibles",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 17, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  vaccines AS metric,\n  total_vaccinations\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "Taux de vaccination de la population",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_fully_vaccinated_per_hundred\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "Nombre de personnes vaccinées par pays",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_fully_vaccinated\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  }
 ]
}